### ISSUE TITLE
Unrecognized option 'map_channel'.

### ISSUE THREAD

**Issue by logsol** [Topslakr/x32Live-CleanUp#2]
Hey I just tried this script but I am getting this error `Unrecognized option 'map_channel'.` Any ideas?

```
➜  x32Live-CleanUp git:(master) ✗ ./Split ~/Dropbox/pulsar/Media/2024/Fusion\ 2024/00000001.WAV
Input File name is /Users/karl/Dropbox/pulsar/Media/2024/Fusion 2024/00000001.WAV
Source Material Sample Rate is
File Name Prefix is ar
Splitting /Users/karl/Dropbox/pulsar/Media/2024/Fusion 2024/00000001.WAV into multiple tracks. This can take a long time depending on the speed of your computer.
Unrecognized option 'map_channel'.
Error splitting the argument list: Option not found
```

**Comment by Topslakr** [comment]
Can you confirm you have ffmpeg and ffprobe on the system?

Each of the lines in the output should be giving you info, like 'Source Material Sample Rate is' should then also say 44100, or 48000. My guess is you're missing a dependency there.

**Comment by logsol** [comment]
<img width="1078" alt="Screenshot 2024-07-02 at 17 12 37" src="https://github.com/Topslakr/x32Live-CleanUp/assets/692826/e7cb843b-f92c-4c4e-86e4-0d78bfc08771">

It looks good, do I need a specific version?

**Comment by Topslakr** [comment]
I wonder... Found a file I can split on my local machine and .. sure enough, it's giving me the same error. I wonder if an output changed in one of the commands. I'll see if I can turn anything up.

**Comment by logsol** [comment]
Oh yeah that must be the case. Glad you are able to reproduce this

**Comment by Topslakr** [comment]
I've updated the script here on GitHub. Can you take a peek to see if it works for you too?

**Comment by logsol** [comment]
✅ Yes! I got it to work! thank you! 👏 

<img width="467" alt="Screenshot 2024-07-02 at 18 13 47" src="https://github.com/Topslakr/x32Live-CleanUp/assets/692826/10704b38-ab4b-4340-a7ce-e17dd8259ec0">

Just FYI I had to run `chmod` on Split, otherwise I would get `permission denied: ./Split`
And also The source file needs to be  in the same directory as the script, otherwise it does not work when proving the path somehow. 

<img width="754" alt="Screenshot 2024-07-02 at 18 16 48" src="https://github.com/Topslakr/x32Live-CleanUp/assets/692826/9ce93383-5a31-426c-9b88-8fd549853972">

But I am happy with that so far! :)

**Comment by logsol** [comment]
Just one more question in your [blog post](https://topslakr.com/2020/03/behringer-x-live-splitting-32-channel-wav-files-and-deleting-silence/) you mentioned the fact that the xlive card creates these 4gb files because of the file system limitation. Is your script somehow capable of concatenating these 4gb multichannel chunks into one before splitting the entire recording into its channels? Or how do you work with this in practice?

**Comment by Topslakr** [comment]
The script could, yes, but I would prefer not to.

Right now, when you run this process it needs 2x the storage while it splits the files. If we first concatenated the source WAV files, you would then need 3x the space. You'd have the source, the concatenated WAVs, and then the split tracks.

It's pretty easy in a DAW to butt the files up to allow for gapless playback so for me, the concatenated source WAVs don't add a lot of value but would require the extra space.

**Comment by Topslakr** [comment]
> ✅ Yes! I got it to work! thank you! 👏
> <img alt="Screenshot 2024-07-02 at 18 13 47" width="467" src="https://private-user-images.githubusercontent.com/692826/345112914-10704b38-ab4b-4340-a7ce-e17dd8259ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NTQxMzAsIm5iZiI6MTcxOTk1MzgzMCwicGF0aCI6Ii82OTI4MjYvMzQ1MTEyOTE0LTEwNzA0YjM4LWFiNGItNDM0MC1hN2NlLWUxN2RkODI1OWVjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQyMDU3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTUwMGU5NjM0YzQwZWZhMzVmMGI2NmQyN2RhNGRjOTZiY2Q5MTZmMjUyNDllYmQ2ZDUxNjIwNWI3ZTQ5YTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GKrNzgereF-II2sBG6yE1dvzWnAsbNtsMi7RybqbQzI">
> 
> Just FYI I had to run `chmod` on Split, otherwise I would get `permission denied: ./Split` And also The source file needs to be in the same directory as the script, otherwise it does not work when proving the path somehow.
> <img alt="Screenshot 2024-07-02 at 18 16 48" width="754" src="https://private-user-images.githubusercontent.com/692826/345113655-9ce93383-5a31-426c-9b88-8fd549853972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NTQxMzAsIm5iZiI6MTcxOTk1MzgzMCwicGF0aCI6Ii82OTI4MjYvMzQ1MTEzNjU1LTljZTkzMzgzLTVhMzEtNDI2Yy05Yjg4LThmZDU0OTg1Mzk3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQyMDU3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2U2OGE4YzdiMjUyYTljZGJlYjg4OTY0ZmZhZTkxNjBlODI4MzM5NDRlMzM5ODhmNjE3NmE5YTNlNjlhMWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tDonzbHVG-rHsYIfqfnss-QlhnzWlsHja8egOaH7rHU">
> 
> But I am happy with that so far! :)

Looks like it's not handling the space in the file name. I'll do some more massaging. Thanks!
